apiVersion: v1
kind: Service
metadata:
  namespace: web-demo
  name: wep-app-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 32223
